# Generated by Django 5.0.1 on 2024-01-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventosapp', '0002_alter_invitados_hora_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitados',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Ingreso'),
        ),
    ]
