# Generated by Django 5.0.2 on 2024-02-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventosapp', '0006_alter_invitados_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
