# Generated by Django 5.0.2 on 2024-02-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventosapp', '0007_evento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitados',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='img/qr'),
        ),
    ]
