# Generated by Django 5.0.2 on 2024-04-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventosapp', '0009_alter_invitados_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitados',
            name='mensaje',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
