# Generated by Django 5.0.2 on 2024-06-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventosapp', '0010_invitados_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
