# Generated by Django 5.0.2 on 2024-06-17 16:27

import Eventosapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventosapp', '0011_evento_imagen_evento_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='img/', validators=[Eventosapp.models.validate_imagen]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', validators=[Eventosapp.models.validate_video]),
        ),
    ]
