# Generated by Django 5.0.2 on 2024-06-17 16:32

import Eventosapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventosapp', '0012_alter_evento_imagen_alter_evento_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.FileField(blank=True, error_messages={'invalid': 'Solo se permiten archivos JPEG para imagen.'}, null=True, upload_to='img/', validators=[Eventosapp.models.validate_imagen]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='video',
            field=models.FileField(blank=True, error_messages={'invalid': 'Solo se permiten archivos MP4 para video.'}, null=True, upload_to='video/', validators=[Eventosapp.models.validate_video]),
        ),
    ]
